#!/bin/bash
# 每晚自动上传学习成果到GitHub

cd /root/.openclaw/workspace

# 配置Git（如果未配置）
git config user.email "bot@openclaw.local" 2>/dev/null || true
git config user.name "好运来博士" 2>/dev/null || true

# 获取当前日期
DATE=$(date '+%Y-%m-%d %H:%M:%S')

echo "[$DATE] 开始上传..."

# 添加所有学习相关文件
git add memory/study/
git add memory/dashboard/
git add auto_study.py
git add auto_git_push.sh

# 检查是否有变更
if git diff --cached --quiet; then
    echo "[$DATE] 没有新内容需要上传"
    exit 0
fi

# 提交
git commit -m "🎓 自动学习更新 | $DATE

- 每日学习笔记
- 技术总结报告  
- 投资分析更新

Generated by 好运来博士"

# 推送到GitHub
if git push origin master 2>&1; then
    echo "[$DATE] ✅ 上传成功"
else
    echo "[$DATE] ❌ 上传失败，检查远程仓库配置"
fi
